import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GlobalProvider } from '@/app/composables/useGlobal'
import { WorkspaceProvider } from '@/app/composables/useWorkspace'
import { BasesProvider } from '@/app/composables/useBases'
import { TablesProvider } from '@/app/composables/useTables'
import { ViewsProvider } from '@/app/composables/useViews'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GlobalProvider>
          <WorkspaceProvider>
            <BasesProvider>
              <TablesProvider>
                <ViewsProvider>
                  {children}
                </ViewsProvider>
              </TablesProvider>
            </BasesProvider>
          </WorkspaceProvider>
        </GlobalProvider>
      </body>
    </html>
  );
}
